# Generated by Django 2.2.2 on 2019-06-19 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=10, verbose_name='Cédula')),
                ('profile_type', models.CharField(choices=[('A', 'Administrador'), ('P', 'Piloto'), ('I', 'Instructor'), ('V', 'Visitante')], max_length=2, verbose_name='Tipo de Usuario')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
