# Generated by Django 2.2.2 on 2019-06-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='cellphone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
