# Generated by Django 2.2.2 on 2019-06-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190619_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'verbose_name': 'Piloto', 'verbose_name_plural': 'Pilotos'},
        ),
    ]
