# Generated by Django 2.2.2 on 2019-06-23 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Destino')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('detaill', models.TextField(verbose_name='Detalle')),
                ('material', models.CharField(max_length=30, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamiento',
            },
        ),
        migrations.CreateModel(
            name='FlyMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='Distancia')),
                ('time', models.TimeField(verbose_name='Tiempo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='missions_destination', to='mission.Destination', verbose_name='Destino')),
                ('equipment', models.ManyToManyField(related_name='missions_equipment', to='mission.Equipment', verbose_name='Equipamiento')),
            ],
            options={
                'verbose_name': 'Mision de Vuelo',
                'verbose_name_plural': 'Misiones de Vuelo',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('type', models.CharField(choices=[('S', 'Super'), ('E', 'Extra'), ('D', 'Diesel')], max_length=30, verbose_name='Tipo')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Combustible',
                'verbose_name_plural': 'Combustibles',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Origen')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Origenes',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('coordinates', models.CharField(max_length=300, verbose_name='Coordenadas')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('objective', models.TextField(verbose_name='Objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_mission', to='mission.FlyMission', verbose_name='Misión')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='planning_plane', to='mission.Plane', verbose_name='Avión')),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
            },
        ),
        migrations.AddField(
            model_name='flymission',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission.Fuel', verbose_name='Gasolina'),
        ),
        migrations.AddField(
            model_name='flymission',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_instructor', to='account.Instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='flymission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='missions_origin', to='mission.Origin', verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='flymission',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_pilot', to='account.Pilot', verbose_name='Piloto'),
        ),
        migrations.AddField(
            model_name='flymission',
            name='routes',
            field=models.ManyToManyField(related_name='missions_route', to='mission.Route', verbose_name='Rutas'),
        ),
    ]
