# Generated by Django 2.2.2 on 2019-06-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
            ],
        ),
        migrations.AddField(
            model_name='flymission',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission.Fuel', verbose_name='Gasolina'),
        ),
    ]
