# Generated by Django 2.2.2 on 2019-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20190619_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='type',
            field=models.CharField(choices=[('S', 'Super'), ('E', 'Extra'), ('D', 'Diesel')], max_length=30, verbose_name='Tipo'),
        ),
    ]
